name: Deploy to GitHub Pages

# Trigger the workflow on push to the master branch
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Rename filter.txt to index.html
      - name: Rename filter.txt to index.html
        run: |
          if [ -f filter.txt ]; then
            mv filter.txt index.html
            echo "Renamed filter.txt to index.html"
          else
            echo "filter.txt not found!"
            exit 1
          fi

      # Step 3: Deploy to GitHub Pages using peaceiris/actions-gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
